server:
  port: 80
spring:
  application:
    name: eureka-custom-web-80
eureka:
  instance:
    instance-id: api.aquiver.com
  client:
    service-url:
      defaultZone : http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka