server:
  port: 9001
spring:
  application:
    name: eurake-custom-web-9001
eureka:
  instance:
    instance-id: eurekaweb9001.com
  client:
    service-url:
      defaultZone : http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka