server:
  port: 8001
#  port: ${random.int[10000,20000]}
rocketmq:
  name-server: 101.200.222.212:9876
  producer:
    group: my-group
    send-message-timeout: 10000
  consumer:
    group: my-group

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.222.212:33060/test01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: dc.342624
    druid:
      validationQuery: SELECT 1
