server:
  port: 7002
spring:
  application:
    name: eurake-server-7002
eureka:
  instance:
    app-group-name: aquiver
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka