server:
  port: 7001
spring:
  application:
    name: eureka-server-7001
eureka:
  instance:
    preferIpAddress: true
    instance-id: eureka7001.com
    appname: server7001
    app-group-name: aquiver
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka